name: Deploy Notificação Trânsito App

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/vanilla-js/notificacao-transito-app-js/**'
  workflow_dispatch:  # Permite executar o workflow manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: examples/vanilla-js/notificacao-transito-app-js  # Caminho correto para a pasta
          branch: gh-pages
          clean: true  # Remove arquivos antigos